export type Camper = {
  id: string,
  name: string,
  price: number,
  rating: number,
  location: string,
  description: string,
  form: 'alcove' | 'panel_van' | 'integrated' | 'semi_integrated',
  length: string,
  width: string,
  height: string,
  tank: string,
  consumption: string,
  transmission: 'automatic' | 'manual',
  engine: 'diesel' | 'petrol' | 'hybrid' | 'electric',
  amenities: string[],
  coverImage: string,
  totalReviews: number,
}